baseURL = 'https://tamrakareen.github.io/devopsinfranklin'
languageCode = 'en-us'
title = 'Devops In Franklin'
theme = 'ananke'

# Parameters for the Ananke theme
[params]
  featured_image = '/images/tnbackground.jpg'
  description = "Welcome to my personal website, where I talk about devops and data enginneering. You might also find sprinklings of my other interests- being a mom to three boys, swimming, learning guitar and french, parenting a child with autism, and living in Franklin, Tennessee."
  favicon = "/images/favicon-16x16.png"
  background_image = "/static/images/tnbackground.jpg"  # Optional: Background image for header
  show_reading_time = true  # Show reading time for posts
  recent_posts_number = 5   # Number of recent posts to display
  ananke_socials = [
    {name = "linkedin", url = "https://linkedin.com/in/tamra-sherwood"},
    {name = "github", url = "https://github.com/tamrakareen"},
  ]  # Social media links in the footer

# Menu configuration (optional, for navigation)
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

# Output formats and other settings
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

# Optional: Enable features like syntax highlighting
[markup]
  [markup.highlight]
    style = "monokai"
[caches]
  [caches.images]
    dir = ':cacheDir/images'
